Configurable DB schema and table prefix
comsysto/eCharm pull request #32
Opened 2023-07-13 13:00 UTC by LarsHaferkampEON

Added especially DB_SCHEMA and DB_TABLE_PREFIX as optional settings in order to be able to integrate the data in an existing DB and schema. This requires the migrations to be deleted from the alembic versions folder. 
I think this folder can be removed/gitignored from the version control. Right now the data is anyway deleted when running a new merge.

Additional with DB_ALEMBIC_RESTRICT_TABLES there is the option to ignore all other tables in the DB except the specific eCharm model tables.

2023-07-14 12:13 UTC, LarsHaferkampEON commented
Currently adding new migrations doesn't work for me, have to check if this is due to the change here

2023-07-14 14:28 UTC, stefanpernpaintner requested changes
@LarsHaferkampEON Will you update README.md? Let me know once you have fixed the "adding new migrations " issue

2023-07-26 10:09 UTC, LarsHaferkampEON commented on README.md
> +    alembic upgrade head
Just tested, with the new implementation it shouldn't try to drop these PostGIS tables

2023-07-27 06:19 UTC, stefanpernpaintner approved these changes

2023-07-27 06:19 UTC, merged